server:
  port: ${SERVER_PORT:8080}

cors:
  origin-patterns: ${ORIGIN_PATTERNS:http://localhost:3000,http://localhost:80,http://localhost:8080}

security:
  jwt:
    token:
      secret-key: 53cr37
      #expire-length: 60000
      expire-length: 3600000

file:
  upload-dir: /home/files-dir

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:postgres-db}
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:example}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:example}@${MONGO_HOST:mongo}:${MONGO_PORT:27017}/
      database: ${MONGO_DB:mongo-db}
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 20MB
      max-request-size: 20MB

springdoc:
  pathsToMatch:
    - /auth/**
    - /**
  swagger-ui:
    use-root-path: true