insert into public.anime (name, episodes) values ('Naruto', 540);
insert into public.anime (name, episodes) values ('Dragon Ball Z', 350);
insert into public.anime (name, episodes) values ('Common green iguana', 1);
insert into public.anime (name, episodes) values ('Possum, common brushtail', 2);
insert into public.anime (name, episodes) values ('Sparrow, rufous-collared', 3);
insert into public.anime (name, episodes) values ('Grizzly bear', 4);
insert into public.anime (name, episodes) values ('Southern lapwing', 5);
insert into public.anime (name, episodes) values ('Carpet snake', 6);
insert into public.anime (name, episodes) values ('Lilac-breasted roller', 7);
insert into public.anime (name, episodes) values ('Heron, giant', 8);
insert into public.anime (name, episodes) values ('Fox, pampa gray', 9);
insert into public.anime (name, episodes) values ('Bent-toed gecko', 10);
insert into public.anime (name, episodes) values ('Otter, canadian river', 11);
insert into public.anime (name, episodes) values ('Squirrel, antelope ground', 12);
insert into public.anime (name, episodes) values ('Sociable weaver', 13);
insert into public.anime (name, episodes) values ('Black rhinoceros', 14);
insert into public.anime (name, episodes) values ('Dragon, frilled', 15);
insert into public.anime (name, episodes) values ('South African hedgehog', 16);
insert into public.anime (name, episodes) values ('Cape white-eye', 17);
insert into public.anime (name, episodes) values ('Mouse, four-striped grass', 18);
insert into public.anime (name, episodes) values ('Pygmy possum', 19);
insert into public.anime (name, episodes) values ('Lizard (unidentified)', 20);
insert into public.anime (name, episodes) values ('Gaur', 21);
insert into public.anime (name, episodes) values ('Warthog', 22);
insert into public.anime (name, episodes) values ('Sheep, stone', 23);
insert into public.anime (name, episodes) values ('Bahama pintail', 24);
insert into public.anime (name, episodes) values ('Ostrich', 25);
insert into public.anime (name, episodes) values ('Baboon, gelada', 26);
insert into public.anime (name, episodes) values ('Blackbuck', 27);
insert into public.anime (name, episodes) values ('Flamingo, roseat', 28);
insert into public.anime (name, episodes) values ('Lourie, grey', 29);
insert into public.anime (name, episodes) values ('Crane, blue', 30);
insert into public.anime (name, episodes) values ('Flamingo, greater', 31);
insert into public.anime (name, episodes) values ('Grouse, greater sage', 32);
insert into public.anime (name, episodes) values ('Kalahari scrub robin', 33);
insert into public.anime (name, episodes) values ('Chipmunk, least', 34);
insert into public.anime (name, episodes) values ('Jackal, asiatic', 35);
insert into public.anime (name, episodes) values ('Armadillo, nine-banded', 36);
insert into public.anime (name, episodes) values ('White spoonbill', 37);
insert into public.anime (name, episodes) values ('Red hartebeest', 38);
insert into public.anime (name, episodes) values ('Eagle, golden', 39);
insert into public.anime (name, episodes) values ('Guerza', 40);
insert into public.anime (name, episodes) values ('Waxbill, black-cheeked', 41);
insert into public.anime (name, episodes) values ('Swallow (unidentified)', 42);
insert into public.anime (name, episodes) values ('White-throated kingfisher', 43);
insert into public.anime (name, episodes) values ('Bird, pied butcher', 44);
insert into public.anime (name, episodes) values ('Lemur, sportive', 45);
insert into public.anime (name, episodes) values ('Black-necked stork', 46);
insert into public.anime (name, episodes) values ('Albatross, waved', 47);
insert into public.anime (name, episodes) values ('Crane, wattled', 48);
insert into public.anime (name, episodes) values ('Owl, great horned', 49);
insert into public.anime (name, episodes) values ('Uinta ground squirrel', 50);
insert into public.anime (name, episodes) values ('Comb duck', 51);
insert into public.anime (name, episodes) values ('Snow goose', 52);
insert into public.anime (name, episodes) values ('Barasingha deer', 53);
insert into public.anime (name, episodes) values ('Pelican, great white', 54);
insert into public.anime (name, episodes) values ('Frog (unidentified)', 55);
insert into public.anime (name, episodes) values ('Dragon, western bearded', 56);
insert into public.anime (name, episodes) values ('Common eland', 57);
insert into public.anime (name, episodes) values ('Trotter, lily', 58);
insert into public.anime (name, episodes) values ('Hoffman''s sloth', 59);
insert into public.anime (name, episodes) values ('Meerkat', 60);
insert into public.anime (name, episodes) values ('Marabou stork', 61);
insert into public.anime (name, episodes) values ('Booby, blue-footed', 62);
insert into public.anime (name, episodes) values ('Goldeneye, barrows', 63);
insert into public.anime (name, episodes) values ('Bird, black-throated butcher', 64);
insert into public.anime (name, episodes) values ('Anteater, giant', 65);
insert into public.anime (name, episodes) values ('Bleu, red-cheeked cordon', 66);
insert into public.anime (name, episodes) values ('Jabiru stork', 67);
insert into public.anime (name, episodes) values ('Tokay gecko', 68);
insert into public.anime (name, episodes) values ('Eastern box turtle', 69);
insert into public.anime (name, episodes) values ('Land iguana', 70);
insert into public.anime (name, episodes) values ('Turtle, eastern box', 71);
insert into public.anime (name, episodes) values ('Stanley crane', 72);
insert into public.anime (name, episodes) values ('Eagle, bateleur', 73);
insert into public.anime (name, episodes) values ('Steenbok', 74);
insert into public.anime (name, episodes) values ('Common boubou shrike', 75);
insert into public.anime (name, episodes) values ('Arctic fox', 76);
insert into public.anime (name, episodes) values ('Red-winged hawk (unidentified)', 77);
insert into public.anime (name, episodes) values ('Palm squirrel', 78);
insert into public.anime (name, episodes) values ('Cat, native', 79);
insert into public.anime (name, episodes) values ('Ibis, glossy', 80);
insert into public.anime (name, episodes) values ('Nyala', 81);
insert into public.anime (name, episodes) values ('Common dolphin', 82);
insert into public.anime (name, episodes) values ('Cape Barren goose', 83);
insert into public.anime (name, episodes) values ('Baboon, olive', 84);
insert into public.anime (name, episodes) values ('Stork, marabou', 85);
insert into public.anime (name, episodes) values ('Long-tailed skua', 86);
insert into public.anime (name, episodes) values ('Blue-tongued lizard', 87);
insert into public.anime (name, episodes) values ('Goose, snow', 88);
insert into public.anime (name, episodes) values ('Lily trotter', 89);
insert into public.anime (name, episodes) values ('Otter, african clawless', 90);
insert into public.anime (name, episodes) values ('Neotropic cormorant', 91);
insert into public.anime (name, episodes) values ('Tiger', 92);
insert into public.anime (name, episodes) values ('Ringtail cat', 93);
insert into public.anime (name, episodes) values ('Trumpeter, green-winged', 94);
insert into public.anime (name, episodes) values ('Alligator, american', 95);
insert into public.anime (name, episodes) values ('Black rhinoceros', 96);
insert into public.anime (name, episodes) values ('Turtle (unidentified)', 97);
insert into public.anime (name, episodes) values ('River wallaby', 98);
insert into public.anime (name, episodes) values ('Deer, roe', 99);
insert into public.anime (name, episodes) values ('Pallas''s fish eagle', 100);
insert into public.anime (name, episodes) values ('Four-spotted skimmer', 101);
insert into public.anime (name, episodes) values ('Klipspringer', 102);
insert into public.anime (name, episodes) values ('Flycatcher, tyrant', 103);
insert into public.anime (name, episodes) values ('Blackbird, red-winged', 104);
insert into public.anime (name, episodes) values ('Cereopsis goose', 105);
insert into public.anime (name, episodes) values ('Hoary marmot', 106);
insert into public.anime (name, episodes) values ('Rat, desert kangaroo', 107);
insert into public.anime (name, episodes) values ('Yak', 108);
insert into public.anime (name, episodes) values ('Carpet python', 109);
insert into public.anime (name, episodes) values ('Stone sheep', 110);
insert into public.anime (name, episodes) values ('Carpet python', 111);
insert into public.anime (name, episodes) values ('Sheep, stone', 112);
insert into public.anime (name, episodes) values ('Bee-eater (unidentified)', 113);
insert into public.anime (name, episodes) values ('Coyote', 114);
insert into public.anime (name, episodes) values ('Rhea, gray', 115);
insert into public.anime (name, episodes) values ('Greater rhea', 116);
insert into public.anime (name, episodes) values ('Blue-tongued lizard', 117);
insert into public.anime (name, episodes) values ('Starling, red-shouldered glossy', 118);
insert into public.anime (name, episodes) values ('Hornbill, leadbeateri''s ground', 119);
insert into public.anime (name, episodes) values ('Boa, emerald green tree', 120);
insert into public.anime (name, episodes) values ('Suricate', 121);
insert into public.anime (name, episodes) values ('Porcupine, indian', 122);
insert into public.anime (name, episodes) values ('Griffon vulture', 123);
insert into public.anime (name, episodes) values ('Long-tailed jaeger', 124);
insert into public.anime (name, episodes) values ('Ferruginous hawk', 125);
insert into public.anime (name, episodes) values ('Nile crocodile', 126);
insert into public.anime (name, episodes) values ('Puffin, horned', 127);
insert into public.anime (name, episodes) values ('Oriental short-clawed otter', 128);
insert into public.anime (name, episodes) values ('Malachite kingfisher', 129);
insert into public.anime (name, episodes) values ('Deer, savannah', 130);
insert into public.anime (name, episodes) values ('Grison', 131);
insert into public.anime (name, episodes) values ('Common zebra', 132);
insert into public.anime (name, episodes) values ('Asian lion', 133);
insert into public.anime (name, episodes) values ('Magpie, australian', 134);
insert into public.anime (name, episodes) values ('Capuchin, brown', 135);
insert into public.anime (name, episodes) values ('Red-necked phalarope', 136);
insert into public.anime (name, episodes) values ('Pintail, white-cheeked', 137);
insert into public.anime (name, episodes) values ('Goose, cape barren', 138);
insert into public.anime (name, episodes) values ('African polecat', 139);
insert into public.anime (name, episodes) values ('Columbian rainbow boa', 140);
insert into public.anime (name, episodes) values ('Squirrel, grey-footed', 141);
insert into public.anime (name, episodes) values ('Warthog', 142);
insert into public.anime (name, episodes) values ('Possum, golden brush-tailed', 143);
insert into public.anime (name, episodes) values ('Cape cobra', 144);
insert into public.anime (name, episodes) values ('Eastern fox squirrel', 145);
insert into public.anime (name, episodes) values ('Phalarope, grey', 146);
insert into public.anime (name, episodes) values ('Ibis, glossy', 147);
insert into public.anime (name, episodes) values ('Quail, gambel''s', 148);
insert into public.anime (name, episodes) values ('Pine snake (unidentified)', 149);
insert into public.anime (name, episodes) values ('Goose, cereopsis', 150);
insert into public.anime (name, episodes) values ('Puma, south american', 151);
insert into public.anime (name, episodes) values ('Burchell''s gonolek', 152);
insert into public.anime (name, episodes) values ('Roe deer', 153);
insert into public.anime (name, episodes) values ('Waxbill, blue', 154);
insert into public.anime (name, episodes) values ('Pale-throated three-toed sloth', 155);
insert into public.anime (name, episodes) values ('Boar, wild', 156);
insert into public.anime (name, episodes) values ('Crown of thorns starfish', 157);
insert into public.anime (name, episodes) values ('Spurfowl, yellow-necked', 158);
insert into public.anime (name, episodes) values ('Caracara (unidentified)', 159);
insert into public.anime (name, episodes) values ('Weaver, sociable', 160);
insert into public.anime (name, episodes) values ('Indian porcupine', 161);
insert into public.anime (name, episodes) values ('Blue wildebeest', 162);
insert into public.anime (name, episodes) values ('Eastern grey kangaroo', 163);
insert into public.anime (name, episodes) values ('Bustard, stanley', 164);
insert into public.anime (name, episodes) values ('Red-billed toucan', 165);
insert into public.anime (name, episodes) values ('Mallard', 166);
insert into public.anime (name, episodes) values ('Burrowing owl', 167);
insert into public.anime (name, episodes) values ('Dama wallaby', 168);
insert into public.anime (name, episodes) values ('Plover, three-banded', 169);
insert into public.anime (name, episodes) values ('Badger, honey', 170);
insert into public.anime (name, episodes) values ('Dove, laughing', 171);
insert into public.anime (name, episodes) values ('Squirrel, eurasian red', 172);
insert into public.anime (name, episodes) values ('Striped dolphin', 173);
insert into public.anime (name, episodes) values ('Cat, european wild', 174);
insert into public.anime (name, episodes) values ('Crocodile, nile', 175);
insert into public.anime (name, episodes) values ('Turtle, long-necked', 176);
insert into public.anime (name, episodes) values ('Leadbeateri''s ground hornbill', 177);
insert into public.anime (name, episodes) values ('Sugar glider', 178);
insert into public.anime (name, episodes) values ('Avocet, pied', 179);
insert into public.anime (name, episodes) values ('Shrew, mandras tree', 180);
insert into public.anime (name, episodes) values ('Stone sheep', 181);
insert into public.anime (name, episodes) values ('Little cormorant', 182);
insert into public.anime (name, episodes) values ('Neotropic cormorant', 183);
insert into public.anime (name, episodes) values ('Butterfly (unidentified)', 184);
insert into public.anime (name, episodes) values ('Savanna baboon', 185);
insert into public.anime (name, episodes) values ('Bottle-nose dolphin', 186);
insert into public.anime (name, episodes) values ('Smith''s bush squirrel', 187);
insert into public.anime (name, episodes) values ('Honey badger', 188);
insert into public.anime (name, episodes) values ('Squirrel, red', 189);
insert into public.anime (name, episodes) values ('Griffon vulture', 190);
insert into public.anime (name, episodes) values ('Dove, laughing', 191);
insert into public.anime (name, episodes) values ('Starling, red-shouldered glossy', 192);
insert into public.anime (name, episodes) values ('Elephant, asian', 193);
insert into public.anime (name, episodes) values ('Burmese brown mountain tortoise', 194);
insert into public.anime (name, episodes) values ('Fairy penguin', 195);
insert into public.anime (name, episodes) values ('Wild turkey', 196);
insert into public.anime (name, episodes) values ('Pale white-eye', 197);
insert into public.anime (name, episodes) values ('Groundhog', 198);
insert into public.anime (name, episodes) values ('Pie, indian tree', 199);
insert into public.anime (name, episodes) values ('American Virginia opossum', 200);
insert into public.anime (name, episodes) values ('Blue and gold macaw', 201);
insert into public.anime (name, episodes) values ('Pademelon, red-legged', 202);
insert into public.anime (name, episodes) values ('Cockatoo, sulfur-crested', 203);
insert into public.anime (name, episodes) values ('Vicuna', 204);
insert into public.anime (name, episodes) values ('Cockatoo, red-tailed', 205);
insert into public.anime (name, episodes) values ('Zorro, azara''s', 206);
insert into public.anime (name, episodes) values ('Turkey, wild', 207);
insert into public.anime (name, episodes) values ('African clawless otter', 208);
insert into public.anime (name, episodes) values ('Water legaan', 209);
insert into public.anime (name, episodes) values ('Catfish, blue', 210);
insert into public.anime (name, episodes) values ('Blacksmith plover', 211);
insert into public.anime (name, episodes) values ('Ovenbird', 212);
insert into public.anime (name, episodes) values ('Wallaby, red-necked', 213);
insert into public.anime (name, episodes) values ('Squirrel, european red', 214);
insert into public.anime (name, episodes) values ('Deer, spotted', 215);
insert into public.anime (name, episodes) values ('Constrictor, eastern boa', 216);
insert into public.anime (name, episodes) values ('Brown capuchin', 217);
insert into public.anime (name, episodes) values ('Dove, white-winged', 218);
insert into public.anime (name, episodes) values ('Waterbuck, defassa', 219);
insert into public.anime (name, episodes) values ('Roseat flamingo', 220);
insert into public.anime (name, episodes) values ('Hornbill, southern ground', 221);
insert into public.anime (name, episodes) values ('Deer, swamp', 222);
insert into public.anime (name, episodes) values ('Buffalo, asian water', 223);
insert into public.anime (name, episodes) values ('Crested barbet', 224);
insert into public.anime (name, episodes) values ('Paca', 225);
insert into public.anime (name, episodes) values ('Hornbill, red-billed', 226);
insert into public.anime (name, episodes) values ('Common langur', 227);
insert into public.anime (name, episodes) values ('Hornbill, yellow-billed', 228);
insert into public.anime (name, episodes) values ('Dove, laughing', 229);
insert into public.anime (name, episodes) values ('House sparrow', 230);
insert into public.anime (name, episodes) values ('Caiman, spectacled', 231);
insert into public.anime (name, episodes) values ('Campo flicker', 232);
insert into public.anime (name, episodes) values ('Bandicoot, southern brown', 233);
insert into public.anime (name, episodes) values ('Raccoon dog', 234);
insert into public.anime (name, episodes) values ('Fox, arctic', 235);
insert into public.anime (name, episodes) values ('Porcupine, indian', 236);
insert into public.anime (name, episodes) values ('Short-nosed bandicoot', 237);
insert into public.anime (name, episodes) values ('Sportive lemur', 238);
insert into public.anime (name, episodes) values ('Cormorant (unidentified)', 239);
insert into public.anime (name, episodes) values ('Cattle egret', 240);
insert into public.anime (name, episodes) values ('Grant''s gazelle', 241);
insert into public.anime (name, episodes) values ('Weaver, chestnut', 242);
insert into public.anime (name, episodes) values ('White-rumped vulture', 243);
insert into public.anime (name, episodes) values ('Magistrate black colobus', 244);
insert into public.anime (name, episodes) values ('Monkey, red howler', 245);
insert into public.anime (name, episodes) values ('Common wolf', 246);
insert into public.anime (name, episodes) values ('Downy woodpecker', 247);
insert into public.anime (name, episodes) values ('Pine siskin', 248);
insert into public.anime (name, episodes) values ('Cormorant, little', 249);
insert into public.anime (name, episodes) values ('Woodpecker, red-headed', 250);
insert into public.anime (name, episodes) values ('King cormorant', 251);
insert into public.anime (name, episodes) values ('Bat, little brown', 252);
insert into public.anime (name, episodes) values ('Ass, asiatic wild', 253);
insert into public.anime (name, episodes) values ('Gray heron', 254);
insert into public.anime (name, episodes) values ('Squirrel, pine', 255);
insert into public.anime (name, episodes) values ('White-cheeked pintail', 256);
insert into public.anime (name, episodes) values ('Hanuman langur', 257);
insert into public.anime (name, episodes) values ('Black-cheeked waxbill', 258);
insert into public.anime (name, episodes) values ('Ringtail cat', 259);
insert into public.anime (name, episodes) values ('Goanna lizard', 260);
insert into public.anime (name, episodes) values ('American beaver', 261);
insert into public.anime (name, episodes) values ('Eurasian hoopoe', 262);
insert into public.anime (name, episodes) values ('Pronghorn', 263);
insert into public.anime (name, episodes) values ('Grey fox', 264);
insert into public.anime (name, episodes) values ('Duiker, common', 265);
insert into public.anime (name, episodes) values ('Eagle, tawny', 266);
insert into public.anime (name, episodes) values ('Coyote', 267);
insert into public.anime (name, episodes) values ('Cuis', 268);
insert into public.anime (name, episodes) values ('Hawk, galapagos', 269);
insert into public.anime (name, episodes) values ('Partridge, coqui', 270);
insert into public.anime (name, episodes) values ('Weaver, sociable', 271);
insert into public.anime (name, episodes) values ('Roller, lilac-breasted', 272);
insert into public.anime (name, episodes) values ('Giraffe', 273);
insert into public.anime (name, episodes) values ('Giant heron', 274);
insert into public.anime (name, episodes) values ('Anteater, australian spiny', 275);
insert into public.anime (name, episodes) values ('Sacred ibis', 276);
insert into public.anime (name, episodes) values ('American marten', 277);
insert into public.anime (name, episodes) values ('Australian pelican', 278);
insert into public.anime (name, episodes) values ('Mongoose, javan gold-spotted', 279);
insert into public.anime (name, episodes) values ('Painted stork', 280);
insert into public.anime (name, episodes) values ('Long-finned pilot whale', 281);
insert into public.anime (name, episodes) values ('Currasow (unidentified)', 282);
insert into public.anime (name, episodes) values ('Puffin, horned', 283);
insert into public.anime (name, episodes) values ('White-eye, pale', 284);
insert into public.anime (name, episodes) values ('Trotter, lily', 285);
insert into public.anime (name, episodes) values ('Large cormorant', 286);
insert into public.anime (name, episodes) values ('Goose, egyptian', 287);
insert into public.anime (name, episodes) values ('Rhinoceros, white', 288);
insert into public.anime (name, episodes) values ('Cow, scottish highland', 289);
insert into public.anime (name, episodes) values ('Darwin ground finch (unidentified)', 290);
insert into public.anime (name, episodes) values ('Sandpiper, spotted wood', 291);
insert into public.anime (name, episodes) values ('Crow, house', 292);
insert into public.anime (name, episodes) values ('Royal tern', 293);
insert into public.anime (name, episodes) values ('Lizard, collared', 294);
insert into public.anime (name, episodes) values ('Tern, white-winged', 295);
insert into public.anime (name, episodes) values ('Puma', 296);
insert into public.anime (name, episodes) values ('Squirrel, golden-mantled ground', 297);
insert into public.anime (name, episodes) values ('Mexican wolf', 298);
insert into public.anime (name, episodes) values ('Pale white-eye', 299);
insert into public.anime (name, episodes) values ('Bustard, kori', 300);
insert into public.anime (name, episodes) values ('Baboon, chacma', 301);
insert into public.anime (name, episodes) values ('Dove, rock', 302);
insert into public.anime (name, episodes) values ('Gull, dusky', 303);
insert into public.anime (name, episodes) values ('Cat, european wild', 304);
insert into public.anime (name, episodes) values ('Boar, wild', 305);
insert into public.anime (name, episodes) values ('Yellow mongoose', 306);
insert into public.anime (name, episodes) values ('Springhare', 307);
insert into public.anime (name, episodes) values ('Macaw, green-winged', 308);
insert into public.anime (name, episodes) values ('Otter, canadian river', 309);
insert into public.anime (name, episodes) values ('Common genet', 310);
insert into public.anime (name, episodes) values ('Squirrel, pine', 311);
insert into public.anime (name, episodes) values ('Antelope, sable', 312);
insert into public.anime (name, episodes) values ('Marmot, yellow-bellied', 313);
insert into public.anime (name, episodes) values ('Nilgai', 314);
insert into public.anime (name, episodes) values ('Bush dog', 315);
insert into public.anime (name, episodes) values ('Springbok', 316);
insert into public.anime (name, episodes) values ('Badger, eurasian', 317);
insert into public.anime (name, episodes) values ('Eastern box turtle', 318);
insert into public.anime (name, episodes) values ('Blue shark', 319);
insert into public.anime (name, episodes) values ('Raven, white-necked', 320);
insert into public.anime (name, episodes) values ('Dabchick', 321);
insert into public.anime (name, episodes) values ('Egret, cattle', 322);
insert into public.anime (name, episodes) values ('Kangaroo, jungle', 323);
insert into public.anime (name, episodes) values ('Capuchin, black-capped', 324);
insert into public.anime (name, episodes) values ('Black-cheeked waxbill', 325);
insert into public.anime (name, episodes) values ('Tyrant flycatcher', 326);
insert into public.anime (name, episodes) values ('Catfish, blue', 327);
insert into public.anime (name, episodes) values ('Cat, jungle', 328);
insert into public.anime (name, episodes) values ('Roller, lilac-breasted', 329);
insert into public.anime (name, episodes) values ('Peacock, blue', 330);
insert into public.anime (name, episodes) values ('Two-banded monitor', 331);
insert into public.anime (name, episodes) values ('Genoveva', 332);
insert into public.anime (name, episodes) values ('Tapir, brazilian', 333);
insert into public.anime (name, episodes) values ('Brown pelican', 334);
insert into public.anime (name, episodes) values ('Gray duiker', 335);
insert into public.anime (name, episodes) values ('Snake, western patch-nosed', 336);
insert into public.anime (name, episodes) values ('Common langur', 337);
insert into public.anime (name, episodes) values ('Musk ox', 338);
insert into public.anime (name, episodes) values ('Hyena, brown', 339);
insert into public.anime (name, episodes) values ('Vulture, king', 340);
insert into public.anime (name, episodes) values ('Common duiker', 341);
insert into public.anime (name, episodes) values ('Stork, white', 342);
insert into public.anime (name, episodes) values ('Coot, red-knobbed', 343);
insert into public.anime (name, episodes) values ('Crake, african black', 344);
insert into public.anime (name, episodes) values ('Bottle-nose dolphin', 345);
insert into public.anime (name, episodes) values ('Cockatoo, red-tailed', 346);
insert into public.anime (name, episodes) values ('Lesser double-collared sunbird', 347);
insert into public.anime (name, episodes) values ('Jackal, silver-backed', 348);
insert into public.anime (name, episodes) values ('Arctic lemming', 349);
insert into public.anime (name, episodes) values ('Black curlew', 350);
insert into public.anime (name, episodes) values ('Woodcock, american', 351);
insert into public.anime (name, episodes) values ('Nuthatch, red-breasted', 352);
insert into public.anime (name, episodes) values ('Trumpeter, green-winged', 353);
insert into public.anime (name, episodes) values ('Land iguana', 354);
insert into public.anime (name, episodes) values ('Australian brush turkey', 355);
insert into public.anime (name, episodes) values ('Brown antechinus', 356);
insert into public.anime (name, episodes) values ('Eagle, pallas''s fish', 357);
insert into public.anime (name, episodes) values ('Bengal vulture', 358);
insert into public.anime (name, episodes) values ('Fringe-eared oryx', 359);
insert into public.anime (name, episodes) values ('Mexican beaded lizard', 360);
insert into public.anime (name, episodes) values ('Jacana, african', 361);
insert into public.anime (name, episodes) values ('Fowl, helmeted guinea', 362);
insert into public.anime (name, episodes) values ('Lemur, sportive', 363);
insert into public.anime (name, episodes) values ('Carpet python', 364);
insert into public.anime (name, episodes) values ('Screamer, southern', 365);
insert into public.anime (name, episodes) values ('Ovenbird', 366);
insert into public.anime (name, episodes) values ('Bush dog', 367);
insert into public.anime (name, episodes) values ('Squirrel, thirteen-lined', 368);
insert into public.anime (name, episodes) values ('Bat, madagascar fruit', 369);
insert into public.anime (name, episodes) values ('Kelp gull', 370);
insert into public.anime (name, episodes) values ('Coatimundi, ring-tailed', 371);
insert into public.anime (name, episodes) values ('Bushbaby, large-eared', 372);
insert into public.anime (name, episodes) values ('Lion, south american sea', 373);
insert into public.anime (name, episodes) values ('Lesser masked weaver', 374);
insert into public.anime (name, episodes) values ('Starling, red-shouldered glossy', 375);
insert into public.anime (name, episodes) values ('Booby, blue-footed', 376);
insert into public.anime (name, episodes) values ('Brazilian otter', 377);
insert into public.anime (name, episodes) values ('Australian brush turkey', 378);
insert into public.anime (name, episodes) values ('Stanley bustard', 379);
insert into public.anime (name, episodes) values ('Emu', 380);
insert into public.anime (name, episodes) values ('Polecat, african', 381);
insert into public.anime (name, episodes) values ('Weaver, red-billed buffalo', 382);
insert into public.anime (name, episodes) values ('Cockatoo, slender-billed', 383);
insert into public.anime (name, episodes) values ('Cormorant, king', 384);
insert into public.anime (name, episodes) values ('Macaque, bonnet', 385);
insert into public.anime (name, episodes) values ('Langur, hanuman', 386);
insert into public.anime (name, episodes) values ('Beaver, north american', 387);
insert into public.anime (name, episodes) values ('Brocket, red', 388);
insert into public.anime (name, episodes) values ('Anteater, australian spiny', 389);
insert into public.anime (name, episodes) values ('Praying mantis (unidentified)', 390);
insert into public.anime (name, episodes) values ('Lizard, blue-tongued', 391);
insert into public.anime (name, episodes) values ('Seal, southern elephant', 392);
insert into public.anime (name, episodes) values ('Gecko, bent-toed', 393);
insert into public.anime (name, episodes) values ('Seal, common', 394);
insert into public.anime (name, episodes) values ('Gazer, sun', 395);
insert into public.anime (name, episodes) values ('Prairie falcon', 396);
insert into public.anime (name, episodes) values ('Lesser flamingo', 397);
insert into public.anime (name, episodes) values ('Australian brush turkey', 398);
insert into public.anime (name, episodes) values ('White-necked raven', 399);
insert into public.anime (name, episodes) values ('Greater blue-eared starling', 400);
insert into public.anime (name, episodes) values ('Northern fur seal', 401);
insert into public.anime (name, episodes) values ('Avocet, pied', 402);
insert into public.anime (name, episodes) values ('Southern brown bandicoot', 403);
insert into public.anime (name, episodes) values ('Yellow baboon', 404);
insert into public.anime (name, episodes) values ('House crow', 405);
insert into public.anime (name, episodes) values ('Turtle, snake-necked', 406);
insert into public.anime (name, episodes) values ('Dolphin, striped', 407);
insert into public.anime (name, episodes) values ('Land iguana', 408);
insert into public.anime (name, episodes) values ('Fringe-eared oryx', 409);
insert into public.anime (name, episodes) values ('Egyptian goose', 410);
insert into public.anime (name, episodes) values ('Snow goose', 411);
insert into public.anime (name, episodes) values ('Gecko, tokay', 412);
insert into public.anime (name, episodes) values ('Rhinoceros, square-lipped', 413);
insert into public.anime (name, episodes) values ('Lizard (unidentified)', 414);
insert into public.anime (name, episodes) values ('Falcon, peregrine', 415);
insert into public.anime (name, episodes) values ('Seal, harbor', 416);
insert into public.anime (name, episodes) values ('Agama lizard (unidentified)', 417);
insert into public.anime (name, episodes) values ('Tayra', 418);
insert into public.anime (name, episodes) values ('Galapagos tortoise', 419);
insert into public.anime (name, episodes) values ('Southern hairy-nosed wombat', 420);
insert into public.anime (name, episodes) values ('Yellow-necked spurfowl', 421);
insert into public.anime (name, episodes) values ('Monster, gila', 422);
insert into public.anime (name, episodes) values ('Gerbil (unidentified)', 423);
insert into public.anime (name, episodes) values ('Sportive lemur', 424);
insert into public.anime (name, episodes) values ('Stork, openbill', 425);
insert into public.anime (name, episodes) values ('Cottonmouth', 426);
insert into public.anime (name, episodes) values ('Indian jackal', 427);
insert into public.anime (name, episodes) values ('Bustard, kori', 428);
insert into public.anime (name, episodes) values ('Pale-throated three-toed sloth', 429);
insert into public.anime (name, episodes) values ('Cow, scottish highland', 430);
insert into public.anime (name, episodes) values ('Echidna, short-beaked', 431);
insert into public.anime (name, episodes) values ('Pine squirrel', 432);
insert into public.anime (name, episodes) values ('Baboon, olive', 433);
insert into public.anime (name, episodes) values ('Feathertail glider', 434);
insert into public.anime (name, episodes) values ('Hawk, ferruginous', 435);
insert into public.anime (name, episodes) values ('Lava gull', 436);
insert into public.anime (name, episodes) values ('Red howler monkey', 437);
insert into public.anime (name, episodes) values ('African skink', 438);
insert into public.anime (name, episodes) values ('Buffalo, asian water', 439);
insert into public.anime (name, episodes) values ('Squirrel, indian giant', 440);
insert into public.anime (name, episodes) values ('Orca', 441);
insert into public.anime (name, episodes) values ('Wattled crane', 442);
insert into public.anime (name, episodes) values ('Otter, african clawless', 443);
insert into public.anime (name, episodes) values ('Screamer, southern', 444);
insert into public.anime (name, episodes) values ('Long-nosed bandicoot', 445);
insert into public.anime (name, episodes) values ('Cobra, egyptian', 446);
insert into public.anime (name, episodes) values ('Fox, cape', 447);
insert into public.anime (name, episodes) values ('Hornbill, yellow-billed', 448);
insert into public.anime (name, episodes) values ('Duiker, gray', 449);
insert into public.anime (name, episodes) values ('Fox, asian red', 450);
insert into public.anime (name, episodes) values ('Dove, little brown', 451);
insert into public.anime (name, episodes) values ('Violet-crested turaco', 452);
insert into public.anime (name, episodes) values ('Crane, blue', 453);
insert into public.anime (name, episodes) values ('Currasow (unidentified)', 454);
insert into public.anime (name, episodes) values ('Sparrow, house', 455);
insert into public.anime (name, episodes) values ('Camel, dromedary', 456);
insert into public.anime (name, episodes) values ('Adouri (unidentified)', 457);
insert into public.anime (name, episodes) values ('Fairy penguin', 458);
insert into public.anime (name, episodes) values ('King cormorant', 459);
insert into public.anime (name, episodes) values ('Rattlesnake, horned', 460);
insert into public.anime (name, episodes) values ('Macaque, pig-tailed', 461);
insert into public.anime (name, episodes) values ('Springhare', 462);
insert into public.anime (name, episodes) values ('Black-crowned crane', 463);
insert into public.anime (name, episodes) values ('Grey-footed squirrel', 464);
insert into public.anime (name, episodes) values ('Hanuman langur', 465);
insert into public.anime (name, episodes) values ('Kangaroo, brush-tailed rat', 466);
insert into public.anime (name, episodes) values ('Phascogale, brush-tailed', 467);
insert into public.anime (name, episodes) values ('White-fronted capuchin', 468);
insert into public.anime (name, episodes) values ('Onager', 469);
insert into public.anime (name, episodes) values ('Langur, gray', 470);
insert into public.anime (name, episodes) values ('Wallaby, agile', 471);
insert into public.anime (name, episodes) values ('Tamandua, southern', 472);
insert into public.anime (name, episodes) values ('Richardson''s ground squirrel', 473);
insert into public.anime (name, episodes) values ('Bat-eared fox', 474);
insert into public.anime (name, episodes) values ('Rhesus macaque', 475);
insert into public.anime (name, episodes) values ('Wolf, timber', 476);
insert into public.anime (name, episodes) values ('Yellow-bellied marmot', 477);
insert into public.anime (name, episodes) values ('Common rhea', 478);
insert into public.anime (name, episodes) values ('Brown capuchin', 479);
insert into public.anime (name, episodes) values ('Lesser double-collared sunbird', 480);
insert into public.anime (name, episodes) values ('Mountain lion', 481);
insert into public.anime (name, episodes) values ('Wolf, timber', 482);
insert into public.anime (name, episodes) values ('Small-spotted genet', 483);
insert into public.anime (name, episodes) values ('Pine siskin', 484);
insert into public.anime (name, episodes) values ('Wallaby, dama', 485);
insert into public.anime (name, episodes) values ('Vulture, griffon', 486);
insert into public.anime (name, episodes) values ('Goose, andean', 487);
insert into public.anime (name, episodes) values ('Yellow-rumped siskin', 488);
insert into public.anime (name, episodes) values ('Collared lizard', 489);
insert into public.anime (name, episodes) values ('Crown of thorns starfish', 490);
insert into public.anime (name, episodes) values ('Burchell''s gonolek', 491);
insert into public.anime (name, episodes) values ('Pocket gopher (unidentified)', 492);
insert into public.anime (name, episodes) values ('Four-striped grass mouse', 493);
insert into public.anime (name, episodes) values ('Cat, toddy', 494);
insert into public.anime (name, episodes) values ('Denham''s bustard', 495);
insert into public.anime (name, episodes) values ('Red-shouldered glossy starling', 496);
insert into public.anime (name, episodes) values ('Caracal', 497);
insert into public.anime (name, episodes) values ('Eagle, tawny', 498);
insert into public.anime (name, episodes) values ('Large-eared bushbaby', 499);
insert into public.anime (name, episodes) values ('Golden brush-tailed possum', 500);
